# Generated by Django 3.0 on 2020-04-28 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0002_answer_relation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='relation',
            new_name='placement',
        ),
    ]
