# Generated by Django 3.0 on 2020-05-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adypu_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(blank=True, max_length=100, null=True)),
                ('subject_code', models.CharField(blank=True, max_length=100, null=True)),
                ('course_type', models.CharField(blank=True, max_length=100, null=True)),
                ('year_of_coding', models.CharField(blank=True, max_length=100, null=True)),
                ('school_name', models.CharField(blank=True, max_length=100, null=True)),
                ('scecialization', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
