# Generated by Django 3.0 on 2020-05-01 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BOS', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adypu_data',
            old_name='scecialization',
            new_name='specialization',
        ),
    ]
