# Generated by Django 2.2.12 on 2020-06-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.onlinewebfonts.com%2Ficon%2F568656&psig=AOvVaw1quSr3Y3FpszKfv2iY-1MN&ust=1592143712183000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCPjD3eD7_ukCFQAAAAAdAAAAABAD', null=True, upload_to=''),
        ),
    ]
