# Generated by Django 2.2.12 on 2020-07-25 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_mc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mc',
        ),
    ]
