# Generated by Django 3.0 on 2020-07-30 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_auto_20200725_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_ans',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personal.UserProfile'),
        ),
    ]
