# Generated by Django 3.0 on 2020-07-30 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_auto_20200730_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_ans',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sub_ans',
            name='sub_name',
        ),
        migrations.AddField(
            model_name='sub_ans',
            name='sub_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personal.Subject'),
        ),
        migrations.CreateModel(
            name='credits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personal.UserProfile')),
                ('subs', models.ManyToManyField(to='personal.sub_ans')),
            ],
        ),
    ]
