# Generated by Django 3.0 on 2020-07-31 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personal', '0007_auto_20200730_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='credit_reg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_subjects', models.ManyToManyField(blank=True, to='personal.Subject')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='sub_ans',
            name='sub_name',
        ),
        migrations.DeleteModel(
            name='credits',
        ),
        migrations.DeleteModel(
            name='sub_ans',
        ),
    ]
