# Generated by Django 3.0 on 2020-08-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0017_auto_20200801_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='image',
            field=models.ImageField(blank=True, default='user.png', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='subject',
            name='price',
            field=models.FloatField(blank=True, default=12.89, null=True),
        ),
    ]
