# Generated by Django 3.0 on 2020-08-02 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0018_auto_20200801_1147'),
    ]

    operations = [
        migrations.DeleteModel(
            name='credit_reg',
        ),
    ]
