# Generated by Django 3.0 on 2020-08-02 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0020_credit_reg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='credit_reg',
        ),
    ]
