# Generated by Django 3.0 on 2020-08-02 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0027_auto_20200802_1517'),
    ]

    operations = [
        migrations.DeleteModel(
            name='certificates',
        ),
    ]
