# Generated by Django 3.0 on 2020-08-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0029_certificates_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
