# Generated by Django 3.0 on 2020-08-06 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0030_auto_20200803_1108'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
