# Generated by Django 3.0 on 2020-04-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECA', '0003_student_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_list',
            name='field',
            field=models.CharField(default='interested', max_length=10),
        ),
    ]
