# Generated by Django 2.2.12 on 2020-05-10 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ECA', '0005_remove_student_list_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_eca',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='add_eca',
            name='status',
        ),
    ]
