# Generated by Django 2.2.12 on 2020-05-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECA', '0006_auto_20200510_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_list',
            name='user',
        ),
        migrations.AlterField(
            model_name='add_eca',
            name='end_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='add_eca',
            name='start_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='feedback',
        ),
        migrations.DeleteModel(
            name='Student_list',
        ),
    ]
